### PR TITLE
feat: Add unconstrain_pars to Model

### PR DESCRIPTION
**Pull request by mjcarter95**
Add unconstrain_pars method to Model instances: this
method transforms a sequence of constrained parameters
from their defined support to unconstrained space.

### CODE REVIEW

**Comment by mjcarter95** [comment]
@riddell-stan @ahartikainen 

The tests pass on MacOS, but fail on Ubuntu (see [here](https://github.com/mjcarter95/pystan-next/runs/1694139227)) - any ideas why this might be happening?

**Comment by riddell-stan** [comment]
Looks like it might be a compile-time gcc problem. This shouldn't be possible (or, rather, it should have surfaced in httpstan). I'll look at it.

**Comment by riddell-stan** [comment]
Found the problem.

```
/usr/bin/ld: cannot find -ltbb
```

Somehow ``httpstan/lib/libtbb.so`` did not get created or stored in the httpstan 4.2.0 linux wheel. I don't know how this happened.

**Comment by riddell-stan** [comment]
I deleted httpstan 4.2.0 from PyPI. Will work on getting 4.3.0 built.

In any event, you'll need to update pyproject.toml so the required version of httpstan is at least 4.3.0.

**Comment by mjcarter95** [comment]
Thank you for looking into this. I'll update pyproject.toml first thing in the morning.

**Comment by riddell-stan** [comment]
The new version is going to be 4.2.1 (not 4.3.0, not sure what I was thinking)

**Comment by riddell-stan** [comment]
httpstan 4.2.1 is being published. I verified (locally) that the compile/build error does not occur on Linux when using your branch.

**Comment by mjcarter95** [comment]
Thank you @riddell-stan. Updated pyproject.toml in the latest commit.

**Review by riddell-stan — APPROVED** [review]

**Pull request merged**
