### PR TITLE
feat: Update pyproject.toml for beta release

### PR DESCRIPTION
**Pull request by riddell-stan**
Major change is the shift from httpstan 1.x to httpstan 2.x.
Other changes are minor, aligning pyproject.toml with httpstan's.

### CODE REVIEW

**Comment by ahartikainen** [comment]
Segfaults

Do we need `--forked` for the pytest? Or is that only a macOS fix?

**Comment by riddell-stan** [comment]
The --forked is needed with clang on httpstan.

**Comment by riddell-stan** [comment]
Running `gdb` on this tells me there is some sort of race condition concerning the temporary directory which gets created to hold a copy of the module. There may be other problems.

**Comment by riddell-stan** [comment]
Found a fix. It involves removing the thread which runs the server in the background and using asyncio throughout. There's a bit of code to write because we are no longer using `requests`.

**Pull request closed without merging**
